# Generated by Django 2.2 on 2019-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
        migrations.AddField(
            model_name='account',
            name='signature',
            field=models.CharField(blank=True, max_length=150, verbose_name='signature'),
        ),
    ]
