# Generated by Django 2.2.1 on 2019-06-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190606_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scheduled_at',
        ),
    ]
