# Generated by Django 2.2 on 2019-05-05 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('date_granted', models.DateTimeField(blank=True, verbose_name='granted')),
                ('recipient_fname', models.CharField(max_length=120)),
                ('recipient_lname', models.CharField(default=None, max_length=120)),
                ('recipient_email', models.CharField(max_length=120)),
                ('certificate_image', models.CharField(default=None, max_length=120)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
