# Generated by Django 2.2.1 on 2019-05-10 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(max_length=120, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='award',
            name='certificate_image',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_granted',
            field=models.DateTimeField(blank=True, verbose_name='date granted'),
        ),
        migrations.AlterField(
            model_name='award',
            name='recipient_email',
            field=models.CharField(max_length=120, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='award',
            name='recipient_fname',
            field=models.CharField(max_length=120, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='award',
            name='recipient_lname',
            field=models.CharField(default=None, max_length=120, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='award',
            name='region',
            field=models.CharField(max_length=120, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='award',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
